### ISSUE TITLE
The Links in the Readme don't work

### ISSUE THREAD

**Issue by donavanbecker** [ratgdo/mqtt-ratgdo#1]
[link in readme](https://github.com/ratgdo/mqtt-ratgdo/blob/449a8a42eccf18a17a63d93c9dac859571c5ef2b/README.md?plain=1#L12-L13), don't take me to a valid place to purchase the board separate.

**Comment by PaulWieland** [comment]
Sorry about that. Some issues separating the source code from the docs.

Please see here: https://paulwieland.github.io/ratgdo/

**Comment by donavanbecker** [comment]
No problem, just figured I would point it out.
