### ISSUE TITLE
WiFi Doesn't Reconnect after Power Cycle

### ISSUE THREAD

**Issue by J-T-W** [ratgdo/mqtt-ratgdo#21]
Using the ratgdo shield with ESP8266 D1 Clone, flashing with the native MQTT, not ESPHome.

During setup, once the flash has complete and the wifi setup phase starts, the device connects to my network quickly and as expected.  Any power cycle thereafter, and the device never reconnects, with the logs just repeating the Wifi attempt ### endlessly.  It doesn't matter where the device is in relationship to the router (I did the flash/setup with the device next to the gd opener to ensure it could communicate, but also within feet of the router itself to rule out interference), after a power cycle it just doesn't reconnect.  Re-flash/setup - connects right away.  I've other ESP32 boards (not same model) on the same network (and one in the same vicinity) an no connection issues with them.  

At a loss and advice would be appreciated.

**Comment by PaulWieland** [comment]
@J-T-W  Can you test the ESP Home firmware as well and see if the same behavior occurs?

**Comment by restauffer** [comment]
I am not an expert by any means but I have read reports of people having such problems when their WAP(S) are advertising the same SSID on both 2.4 & 5gHz. If your WAP is doing so, temporarily disable the 5ghz radio and see if the problem goes away. If it does, and you can create multiple SSID's per radio, create a new SSID just for the 2.4gHz radio. Keep the old one in use for 2.4 and 5gHz so previous equipment continues to operate as before. Use the new 2.4-only SSID for your esp8266.

**Comment by J-T-W** [comment]
Thank you for the guidance.  My primary network uses different SSIDs already for the 2.4 & 5 bands, and I can duplicate this issue on a completely different stand-alone 2.4 network with SSID different from the primary networks. 

Flashed with the ESPHome version, and although it takes a hot minute after a power cycle, it does connect as expected!  So - yeah!  :-)
