### ISSUE TITLE
Very sporadic response to door commands

### ISSUE THREAD

**Issue by sjhill01** [ratgdo/mqtt-ratgdo#37]
Using MQTT with mosquitto, I can watch the topics with MQTT explorer and see the commands being sent, but it often takes 4 or 5 attempts before the garage door reacts. As far as I can tell the status is timely, it's just commands that are unreliable. It seems like it might ignore a few then finally react, then it's "awake" and reacts normally for a while after that, but that's pretty anecdotal.

This is with 2.54 and what I believe is a Security 2.0 GDO (Chamberlain B550).

**Comment by PaulWieland** [comment]
Upgrade to v2.55
