### ISSUE TITLE
getting erroneous light messages on a 8500 setup within the same second on/off

### ISSUE THREAD

**Issue by thplex48178** [ratgdo/mqtt-ratgdo#46]
Hi, 

I seem to be getting some messages in the ha logbook that the light status changed to on and then off in the same second. This is nowhere near any action on the Door, so like no opening or closing.  I don't know if the light really turns on or off.

has anyone else seen this ?  The Opener function seems stable so far across the 3 doors, also wondering if the issue could be related to the fact that these are linked, meaning if one door opens all three light modules turn on for each of the doors.

The on/off message is nowhere near any action on any other door either, also event seems way to short to be real ? same second ?

thanks

**Comment by PaulWieland** [comment]
Sec + 1 gdos are notorious for reporting invalid information on the serial line. I implemented a change that requires two consequitive matching messages for the door status. I guess I need to add it to the light and lock status as well.
