### ISSUE TITLE
doesn't work with Genie 7055 opener, causes lockout of panel as well

### ISSUE THREAD

**Issue by changes13** [ratgdo/mqtt-ratgdo#52]
Tried with v1 and v2 security.  In both cases, the motor locks out any operation, even from the panel.  ratgdo operations dont work.

Panel: ![PXL_20240104_234238589](https://github.com/ratgdo/esphome-ratgdo/assets/113197804/ba034370-147d-4ed5-8c79-c7ba37f89ed1)
motor: https://www.geniecompany.com/garage-door-opener-/model-7055
log with v1 sec : [7055-v1.txt](https://github.com/ratgdo/esphome-ratgdo/files/13836491/7055-v1.txt)

**Comment by PaulWieland** [comment]
Genie openers are not chamberlain security plus. You have to use the dry contact wiring and control protocol.

**Comment by changes13** [comment]
I changed the config to dry contact.  Same behavior.  Is there something else I should try?
