### ISSUE TITLE
Firmware update links to wrong repo

### ISSUE THREAD

**Issue by danb35** [ratgdo/mqtt-ratgdo#55]
When I browse to the ratgdo web interface, the first item on the page is the OTA firmware update, where the text on the page says to "Download the latest .bin file from GitHub."  But "GitHub" there is a link to https://github.com/PaulWieland/ratgdo/releases, not to this repo's releases page.  This is under firmware 2.57 on hardware version 2.5.

**Comment by PaulWieland** [comment]
Yup, thanks for pointing that out. It should be `https://github.com/ratgdo/mqtt-ratgdo/releases`
Will be fixed in next release.
