### ISSUE TITLE
Is it safe\certified to update to the latest ESPHome versions?

### ISSUE THREAD

**Issue by bthome** [ratgdo/mqtt-ratgdo#88]
In Home Assistant it shows that both of my ratgdo's have "Update Available".  Is it safe to maintain parity with esphome versions with ratgdo?  Last time I updated it wouldn't OTA update so had to drag a laptop out to the garage on a ladder and plug in to do a local update.  

Do you certify or give the ok to update to the latest esphome as they come out?

Thanks...been using ratgdo for months and not a single issue.  Appreciate your innovation.

**Comment by PaulWieland** [comment]
This is the MQTT-ratgdo repo... but to answer your question, it should be fine to update if you have a reason to.
