### ISSUE TITLE
Lost control on 2 of the 4 RatGDO units

### ISSUE THREAD

**Issue by skykep** [ratgdo/mqtt-ratgdo#90]
2 of my 4 units are on Craftsman belt-driven overhead units.  Flashed with 2.57 MQTT firmware and set for security + 2.0 (yellow buttons).  Worked for a bit, but today I discovered that these two Craftsman units are no longer responding to commands.  They still report status of door and light (although very delayed), and the wall-mounted door openers still work fine.

**Comment by PaulWieland** [comment]
Try and reflash with full erase to see if a new randomly generated client ID fixes the problem.

**Comment by skykep** [comment]
> Try and reflash with full erase to see if a new randomly generated client ID fixes the problem.

Yep, did that and it works for a few days, but ultimately ends up losing control again.

**Comment by skykep** [comment]
Any way I can pull logs off it to help?  Just seems like it's losing the rolling code for control because the status hasn't stopped working at all.

**Comment by PaulWieland** [comment]
I dont think its losing the rolling code, its just using a bad seed. There is some difference in the way the random rolling code is initialized between the esphome version and this version that I have to look into.

Until I figure it out, the only way to get a new random code with the mqtt firmware is to do a full erase and reflash.

Alternatively you can enable MQTT support in the esphome version and use that instead.

**Comment by skykep** [comment]
Oh, that's some good news.  I'll give that a shot for now and report back.
