### ISSUE TITLE
security 1.0 ratdgo mqtt door lock challenges for homeassistant

### ISSUE THREAD

**Issue by shbertin** [ratgdo/mqtt-ratgdo#92]
hey team, 
hear me out, been trying to figure this out, and i'm at my wits end here.  I thought I'm close, but maybe not.

here's the situation:
I have two garage doors, one is with a yellow button (we don't have to talk about that one anymore as it's on esphome and working as expected)
the second one is with a purple button and only supports the mqtt (hence my dilemma).

I also have homeassistant and hubitat and so here in-lies my issue.
with mqtt and homeassistant, everything seems to work as expected, upon discovery, it shows 
![Screenshot 2024-07-22 at 4 52 27 PM](https://github.com/user-attachments/assets/37338e6d-01ce-41ac-a0ee-66b71750783b)

--- that is working fine (so long as mqtt server stays on line (another issue for another day).

with hubitat, i've also got it setup to utilize the mqtt server as I want the lock functionality as I set a schedule to lock both my doors overnight.
![Screenshot 2024-07-22 at 4 53 56 PM](https://github.com/user-attachments/assets/49bca1d2-8f48-4548-8e10-90b0a09997c3)

this is working as expected, and sometimes fails, and I need to reset the entire db.  Needless to say, i was trying to get everything connected through homeassistant and here is where I need some assistance as I've been playing with this for over a couple of days.

I went into the configuration.yaml in homeassistant and created the following:
![Screenshot 2024-07-22 at 4 55 39 PM](https://github.com/user-attachments/assets/5d8076a2-9cb6-4f81-bf1c-828c26d2aa76)

when i run the entity, it goes and uses the hubitat code and is able to successfully lock the garage door, but when I go to use it and try to add it to a dashboard I get the following error:
![Screenshot 2024-07-22 at 5 04 32 PM](https://github.com/user-attachments/assets/0e004f9d-e266-4a46-83f9-d384f1b0af5f)

the funny part though, is that it is working as expected, so I thought I was there:
![Screenshot 2024-07-22 at 5 03 47 PM](https://github.com/user-attachments/assets/e29a77b2-82fa-4670-bd7a-70ab28763222)

I have been trying through multiple iterations to get it to work with mqtt through homeassistant itself (removing hubitat from the picture) and not had any success:
![Screenshot 2024-07-22 at 5 07 55 PM](https://github.com/user-attachments/assets/7d8b45fc-c049-4f11-a7af-548688f59b69)

i'm not sure if anyone has done this before, and/or has any advice to provide, but i'm all ears.  i can share more of what i've done if anyone is interested on the hubitat side of things as well.

Thank you kindly,
Shawn

**Comment by PaulWieland** [comment]
> the second one is with a purple button and only supports the mqtt (hence my dilemma).

[Security + 1.0 support was added to ESPHome in January](https://github.com/ratgdo/esphome-ratgdo/pull/171).

I would suggest switching to ESPHome if you are using Home Assistant.
