### ISSUE TITLE
Unresponsive every 3-4 months

### ISSUE THREAD

**Issue by neldonado** [ratgdo/mqtt-ratgdo#93]
I am using the ratgdo 2.53 with security 1 garage door opener. I am using the mqtt with mosty good results, however I am running into the same issue every 3-4 months. I can't seem to figure out what's causing it, maybe others are facing similar issues and can chime in. But This is the third time in about a year where my garage door will start opening and closing every minute. The garage door opening becomes unresponsive and I have to unplug the controller and reflash the firmware. After this I am good for another 3-4 months.

**Comment by skykep** [comment]
Not the same issue, but somewhat similar in where mine will stop controlling.  Still reads the status fine but unable to control 2 Craftsman belt-driven openers.  They work for a couple days and then quit.  The two wall-mounted Liftmaster units on my overhead doors still control fine.

Paul has not responded to any of my emails over the last month since I installed these.  Very frustrating to give someone money and they ghost their own product.

**Comment by neldonado** [comment]
> Not the same issue, but somewhat similar in where mine will stop controlling.  Still reads the status fine but unable to control 2 Craftsman belt-driven openers.  They work for a couple days and then quit.  The two wall-mounted Liftmaster units on my overhead doors still control fine.
> 
> 
> 
> Paul has not responded to any of my emails over the last month since I installed these.  Very frustrating to give someone money and they ghost their own product.

Just out of curiosity, what's your Wi-Fi set up like? part of me is wondering if the device is getting bounced around to my different access points and just dropping out somehow but I haven't been able to figure out or reproduce it. It just will randomly happen. the first time, it opened up my garage door at 1 o'clock in the morning and set off my whole Home alarm .

**Comment by PaulWieland** [comment]
@neldonado what control protocol are you using?

**Comment by skykep** [comment]
> Just out of curiosity, what's your Wi-Fi set up like? part of me is wondering if the device is getting bounced around to my different access points and just dropping out somehow but I haven't been able to figure out or reproduce it. It just will randomly happen. the first time, it opened up my garage door at 1 o'clock in the morning and set off my whole Home alarm .

I have an access point within 10 feet of these units, so it's not changing access points.  I haven't had it open or close my doors randomly, fortunately.  If that were the case, I would rip these out immediately and demand a fix or a refund.  I'm trying to be patient for a fix because at least the status reporting is working fine.

**Comment by skykep** [comment]
> @neldonado @skykep what control protocol are you using?

MQTT.  Supposedly this isn't so much of an issue for those using ESPHome.

**Comment by PaulWieland** [comment]
> > @neldonado @skykep what control protocol are you using?
> 
> MQTT. Supposedly this isn't so much of an issue for those using ESPHome.

Threats not a control protocol. It’s either sec +1, 2 or dry contact.

**Comment by neldonado** [comment]
> @neldonado @skykep what control protocol are you using?

@PaulWieland security +1

**Comment by skykep** [comment]
Security + 2.0 for all four of mine.  Two of them work fine.

**Comment by PaulWieland** [comment]
> security +1

What firmware version?

**Comment by neldonado** [comment]
> > security +1
> 
> 
> 
> What firmware version?
> 
> 
> 
> 
> 
> 
> 
> 

V2.57 for hardware v2.50

**Comment by PaulWieland** [comment]
skykeps issue is completely unrelated to the original reported issue. Deleting that part of the thread to clean this up, as there is already a separate open issue.

**Comment by PaulWieland** [comment]
It only happening after months is really odd. I wonder if it's a capacitor failure in your wall control panel which is causing your wall panel to brown out & reboot. What model is your wall control panel?

**Comment by neldonado** [comment]
> It only happening after months is really odd. I wonder if it's a capacitor failure in your wall control panel which is causing your wall panel to brown out & reboot. What model is your wall control panel?

Chamberlain LiftMaster Residential Jackshaft Opener Model 3800. The opener is powered through the battery backup which plugs into the wall. Could I still be having brown out? I don't have the ratgdo board on a UPS however.

**Comment by neldonado** [comment]
> It only happening after months is really odd. I wonder if it's a capacitor failure in your wall control panel which is causing your wall panel to brown out & reboot. What model is your wall control panel?

Chamberlain LiftMaster Residential Jackshaft Opener Model 3800. The opener is powered through the battery backup which plugs into the wall. So I can shut off the breaker and the garage door functions fine.

**Comment by neldonado** [comment]
> It only happening after months is really odd. I wonder if it's a capacitor failure in your wall control panel which is causing your wall panel to brown out & reboot. What model is your wall control panel?

I have a family member in the garage door business and they think it could just be due to age forgetting the rolling codes and spamming open / close. I am going to reset the controller and monitor this.

**Comment by PaulWieland** [comment]
Your GDO doesn't use rolling codes for wireline control

**Comment by neldonado** [comment]
> Your GDO doesn't use rolling codes for wireline control

Right, what I am saying is I think this may be unrelated to the ratgdo board. The technician said when it opens and closes randomly it's a sign of the controller losing the rolling code of the wireless openers and just picking up signals from nearby controllers. Something you normally only see with older devices that haven't been serviced in a long time. He walked me through holding the purple learn button to reprogram everything. If it happens after that then maybe it does have something to do with the ratgdo? unless you think otherwise.

**Comment by sile16** [comment]
Also, experienced 2 of the 3 doors became unresponsive.   Here is the logbook from home assistant and also the mqqt status.    After a simple power cycle of the device it starts working again.

ratgdo v2.57 for hardware v2.50 , mqqt version
Security + 1.0
Chamberlain Liftmaster 

<img width="404" alt="image" src="https://github.com/user-attachments/assets/afa31db9-4cdb-4ad1-936e-9d3f85a4adec">

door status stuck in "sycing"
<img width="177" alt="image" src="https://github.com/user-attachments/assets/aabb3b7b-9f0b-4ae9-a716-128a5be3646d">

**Comment by thenakuls** [comment]
I have secplus 1 GDO  889LM control panel and I have noticed that after a power blip (very short power outage causing garage door to restart) ratgdo stops working, most probably because it goes in emulation mode.

@PaulWieland would adding an option of adding a delay after reboot help?

**Comment by neldonado** [comment]
@PaulWieland just to keep you in the loop on odd behavior I've been having. I had some power flickers last night, nothing shut off (to my knowledge no UPS alerts on my other equipment), but I'm wondering if it was enough to mess up the ratgdo. This morning I opened my garage door and the status was stuck on "Closed". Logging into the web server for it I was able to remotely reboot the device, and all worked fine after that. I'm wondering if simply getting a small UPS would fix these issues I'm having.

**Comment by neldonado** [comment]
Again had my door randomly open / close last night. ![image](https://github.com/user-attachments/assets/c5aec082-974e-4fc9-82f3-bf6e9933d0ad)

It didn't actually open on its own until 6:30am (not even captured in the logs, caught on my camera)

**Comment by PaulWieland** [comment]
See my comment above.

**Comment by neldonado** [comment]
![image](https://github.com/user-attachments/assets/8814e3f6-a465-41c2-94fc-1e71d15b3b1e)

It's just a few seconds between "was opened, was closed"

**Comment by PaulWieland** [comment]
Have you tried unhooking your wall panel or replacing it?

**Comment by neldonado** [comment]
> it?

Are you talking about this? If so, no, but I will!

![image](https://github.com/user-attachments/assets/67c4e510-0d56-4bd7-acd4-9c51bcc14205)
