### ISSUE TITLE
Unresponsive & won't sync - logs show "Component ratgdo took a long time..."

### ISSUE THREAD

**Issue by judetf** [ratgdo/mqtt-ratgdo#95]
Using ESPHome in HA
Hardware: 2.51
Firmware: 2.5i (ESPHome 2024.7.3)

Everything was working and then HA stopped controlling, but shows states correctly. I go to the webpage and same thing - states are correct, but controls don't work. The rolling counter code is around 2000. I click the 'sync' button and I get this set of responses, repeated about 5 times while the sync counter increments, but then it all stops:
12:11:59 | [D] | [ratgdo_secplus2:213] | Query paired devices of type: ALL
12:11:59 | [D] | [ratgdo_secplus2:213] | Query paired devices of type: REMOTE
12:11:59 | [D] | [ratgdo_secplus2:213] | Query paired devices of type: KEYPAD
12:11:59 | [D] | [ratgdo_secplus2:213] | Query paired devices of type: WALL_CONTROL
12:11:59 | [D] | [ratgdo_secplus2:213] | Query paired devices of type: ACCESSORY
12:11:59 | [W] | [component:237] | Component ratgdo took a long time for an operation (149 ms).
12:11:59 | [W] | [component:238] | Components should block for at most 30 ms.

After that block repeats a bunch of times it finally ends with:
12:12:03 | [W] | [ratgdo_secplus2:107] | Triggering sync failed actions.
12:12:03 | [W] | [component:237] | Component ratgdo took a long time for an operation (150 ms).
12:12:03 | [W] | [component:238] | Components should block for at most 30 ms.

The errors are always on component 237 and 238...

Any suggestions? Thanks!
jtf

**Comment by PaulWieland** [comment]
You are using the ESP Home firmware. This is the MQTT firmware repo.
