### ISSUE TITLE
command:query does not appear to work

### ISSUE THREAD

**Issue by jeremy44** [ratgdo/mqtt-ratgdo#97]
When I sent a MQTT message to my RATGDO [ratgdo v2.59 for hardware v2.50 Security 2.0] nothing subsequently happens, I'm expecting a message to be published to '[Device Name]/status/door'.  I'm following the directions published here: 

https://paulwieland.github.io/ratgdo/01_features.html

That is, publishing a query message to a topic '[Device Name]/command' with the body of 'query'. 

Thanks in advance.

**Comment by michaeljoos72** [comment]
For me '[Device Name]/command/command:query' does work --> 2x command

![image](https://github.com/user-attachments/assets/b21a31be-6b2a-4a3a-a0c9-8cad8c88dd3a)

**Comment by jeremy44** [comment]
@michaeljoos72 Thanks so much.  That worked. That wasn't clear to me from the documentation or the code.  Appreciate it.
